### ISSUE TITLE
Substantiate web assembly speed

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#10]
In the first blog we claim web assembly is not significantly slower than native C++, we should point to a study which substantiate this.

I found
* https://arxiv.org/abs/1901.09056 , wasm 1.5x slower native
* https://youtu.be/aC_QLLilwso , prime example

**Comment by jspaaks** [comment]
Do we need something else besides how it's formulated now? https://github.com/NLESC-JCER/run-cpp-on-web/blame/322ad01f1f716c0afa9893b3ab82c3f6dc6e9149/run-your-c%2B%2B-code-on-the-web/README.md#L39-L40
If not, I suggest we close this issue.

**Comment by sverhoeven** [comment]
Acceptable penalty is fine.
