### ISSUE TITLE
Minor remarks

### ISSUE THREAD

**Issue by daanboer** [NLESC-JCER/run-cpp-on-web#108]
Thank you for creating this series of blog posts, they have already been very helpful. I want to share some minor remarks that I encountered while working with the posts. 

#### C++ related
It is quite unconventional to include a .cpp file (and it can e.g. lead to "multiple definition" errors). This can be solved by creating a file `algebra.h` that declares the functions:

```cpp
#ifndef ALGEBRA_H
#define ALGEBRA_H

float equation(float x);
float derivative(float x);

#endif
```

then include this file from `algebra.cpp` and `newtonraphson.cpp`.

#### Minor remarks
 - Line 96: `'answer'` -> `'container'`
 - Line 100: a word is missing (e.g. should _look_ like)

#### C++ related
 - Same remarks as for the first blog post.

**Comment by sverhoeven** [comment]
All suggestions have been incorporated into #113 PR, please have a look if the implementation is OK.
