### ISSUE TITLE
how to make root finding slow for long running tasks

### ISSUE THREAD

**Issue by jspaaks** [NLESC-JCER/run-cpp-on-web#11]
or should we choose monte carlo estimation of pi instead? I do think it would be best to stick with one algorithm throughout all blogs if we can.

**Comment by sverhoeven** [comment]
We could use pi code made by @fdiblen at https://github.com/fdiblen/cpp2wasm-benchmark#the-c-code

A different algorithm will also make it easier to benchmark the web assembly speed (#10).

**Comment by sverhoeven** [comment]
For now we will stay with NewtonRaphson using a sleep in C++ code.

**Comment by jspaaks** [comment]
I think we can close this.

**Comment by sverhoeven** [comment]
Done
