### ISSUE TITLE
algebra.*

### ISSUE THREAD

**Issue by janvdijk** [NLESC-JCER/run-cpp-on-web#110]
A few more nits on the C++ code.

 * I concur with Daan that `algebra.cpp` is better included through a header. Or, in this case, it may be better to just make the `equation` and `derivative` functions members of the Newton-Raphson class altogether and ditch `algebra.cpp` altogether, since the expressions are hardcoded anyway.
 * If `algebra.cpp` is kept: I found the name confusing.. How about `problem.cpp`, since that is what it defines?
 * The function `equation` is better renamed into `function` or expression, since it becomes an equation only after requiring it be equal to zero.

**Comment by sverhoeven** [comment]
In the bindings and in later in JavaScript we implement functions, I wanted to reserve the word `function` for defining JS functions.
So I will keep calling it `equation`. 

The posts to have been refactored to use  `problem.hpp`, see PR #113 for the changes.
