### ISSUE TITLE
createModule

### ISSUE THREAD

**Issue by janvdijk** [NLESC-JCER/run-cpp-on-web#111]
When I was trying the webassembly blog, the emscripten invocation puzzled me: the argument `createModule` sounds like it may be a reserved name that cannot and should not be changed. In reality, this is just the name that is attached to the particular functionality that is exposed, IIUC. This could be made clear by using (for example) `createNewtonRaphsonModule` throughout. (The same goes for the other blogs.)

**Comment by sverhoeven** [comment]
Resolved by explaining createModule after emcc command.
