### ISSUE TITLE
Python webserver deployment instructions

### ISSUE THREAD

**Issue by janvdijk** [NLESC-JCER/run-cpp-on-web#112]
This one is related to the deployment using the python web server. If you follow the instructions literally, typing `python3 -m http.server 8000`, the process runs in the foreground. Since I wanted to see console output, I instead started it from a different console --- but failed to change to directory that contains the required files.

Maybe it could be explicitly stated that the command creates a web server *that uses the pwd as root*; that is serves documents such as `index.html` and `scatter.html` in the directory from which the server was started? Or perhaps add a `&` to the suggested command, so the process will run in the background and the console is available for subsequent commands?

**Comment by sverhoeven** [comment]
Added cwd and cd note in https://github.com/NLESC-JCER/run-cpp-on-web/pull/113/commits/5376ad60924a9963bca99b45dd1353afae999e89
