### ISSUE TITLE
BTW is anyone bothered by my indent style

### ISSUE THREAD

**Issue by jspaaks** [NLESC-JCER/run-cpp-on-web#15]
I changed it from what Stefan had (which I believe was compliant with conventions). Maybe we should ask the C++ peeps.

**Comment by sverhoeven** [comment]
I would suggest we use the defaults of [clang-format](https://clang.llvm.org/docs/ClangFormat.html). So double space indents.

Whatever format we pick is fine, they should just be consistent

**Comment by jspaaks** [comment]
If find the header particularly badly formatted when sticking to conventions:

```cpp
#ifndef H_NEWTONRAPHSON_H
#define H_NEWTONRAPHSON_H

#include <string>

namespace rootfinding {
class NewtonRaphson {
public:
  NewtonRaphson(double tolerancein);
  double solve(double xin);

private:
  double tolerance;
};
} // namespace rootfinding
#endif
```

Compared to what we have now:


```cpp
#ifndef H_NEWTONRAPHSON_H
#define H_NEWTONRAPHSON_H

#include <string>

namespace rootfinding {
   class NewtonRaphson {
      public:
         NewtonRaphson(double tolerancein);
         double solve(double xin);
      private:
         double tolerance;
  };
}
#endif
```

Seems like these C++ people really like to hurt themselves

**Comment by sverhoeven** [comment]
That is indeed bad, tried all of the [styles](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) and they all don't indent namespaces. The `Microsoft` style looks least bad.

**Comment by jspaaks** [comment]
Leave it as it is now, unless the C++ reader really complain
