### ISSUE TITLE
Do we care about initial_guess = 1.5 yielding NaN?

### ISSUE THREAD

**Issue by jspaaks** [NLESC-JCER/run-cpp-on-web#16]
Also, I'd suggest we pick an initial value within the bounds of the image -4 \< x \< 4

**Comment by jspaaks** [comment]
could be solved by making ``derivative`` more complicated (and arbitrary)

**Comment by jspaaks** [comment]
looks like ``emcc``'s `` -s DISABLE_EXCEPTION_CATCHING=1 ``option could help throw exceptions. Here, we're getting a NaN because C++ defines divide by zeor result as NaN.

**Comment by sverhoeven** [comment]
Using iterations from #19 shows following

For initial_guess = 0
```js
[{x: 0, y: 2, slope: 0, delta_x: Infinity},
{x: -Infinity, y: -Infinity, slope: Infinity, delta_x: NaN}]
```

For initial_guess 1.5
```js
[{x: 1.5, y: 3.125, slope: 3.75, delta_x: 0.8333333333333334},
{x: 0.6666666666666666, y: 1.8518518518518519, slope: 0, delta_x: Infinity},
{x: -Infinity, y: -Infinity, slope: Infinity, delta_x: NaN}]
```

**Comment by jspaaks** [comment]
I guess the answer to the original question is 'No'. Should we close this?

**Comment by sverhoeven** [comment]
Deal with it in exception blog
