### ISSUE TITLE
store the iterations in NewtonRaphson class

### ISSUE THREAD

**Issue by jspaaks** [NLESC-JCER/run-cpp-on-web#18]
keep track of the (x, y, y') as public property ``iterations`` array of struct?

```
iterations[0].x
iterations[0].y
iterations[0].dy
```

Issue that triggered this #16

**Comment by sverhoeven** [comment]
Nice, we could plot the iterations with vega, instead of doing nonsensical timing runs.

**Comment by jspaaks** [comment]
WIP PR #19

**Comment by sverhoeven** [comment]
Iterations (using #19) of solve using initial guess of -20 gives in [vega lite editor](https://vega.github.io/editor/#/gist/bb1265a9a0b0ec7bd0bdc92d4bdc5c76/spec.json)

**Comment by sverhoeven** [comment]
![visualization](https://user-images.githubusercontent.com/1713488/91982278-4af1ee80-ed2a-11ea-83bc-1530dbe02928.png)

**Comment by jspaaks** [comment]
Can we close this? Since we have https://github.com/NLESC-JCER/run-cpp-on-web/blob/e023624a402e0468f4968e5aa2b45981aa872700/js-plot/newtonraphson.cpp#L15

**Comment by sverhoeven** [comment]
Done in plot blog
