### ISSUE TITLE
write js-webapp-async.md

### ISSUE THREAD

**Issue by jspaaks** [NLESC-JCER/run-cpp-on-web#2]
- Long running JS web application js-async.md
- point to problem of blocking (assume content exists already); mention solution async 
- web worker

**Comment by sverhoeven** [comment]
Use sleep in C++ code to demonstrate blocking.

**Comment by cwmeijer** [comment]
Added sleep code in C++ code in ee3cef915347efcd36ff303cb3d298d630d18913.

**Comment by sverhoeven** [comment]
Blog is far enough so this can be closed
