### ISSUE TITLE
Adding gist

### ISSUE THREAD

**Issue by fdiblen** [NLESC-JCER/run-cpp-on-web#24]
Do we want to add gist on GitHub and add links to those in the blog post?

**Comment by sverhoeven** [comment]
Do you mean [GitHub gist](https://gist.github.com/)? 
Yes, we can use gists to add code snippets to a medium story. 

I see other blogs at https://blog.esciencecenter.nl/ use `<pre>` tag without coloring and line numbers, that could also work for us.

If we do this, lets make gists when we publish to medium, as keeping the gists and the readmes in-sync is not something I want to deal with now.

**Comment by jspaaks** [comment]
I do like highlighting in these snippets, if we go with ``pre`` we should make sure it has that. If not, we should use gists IMO.

**Comment by sverhoeven** [comment]
Tried with manual gist. Which works, will need to make a lot of gists. 

Lets try out a embedding with code higlighting and line numbers, without using gist.

**Comment by sverhoeven** [comment]
Will do when publishing to medium
