### ISSUE TITLE
Replace math function with one with nicer shape

### ISSUE THREAD

**Issue by cwmeijer** [NLESC-JCER/run-cpp-on-web#33]
We want to have a mathematical function that shows a nice dip to illustrate the goal of the Newton-Raphson method well. This function should be used in every blog. We prefer consistent use of the function, consistent scaling, consistent style (all if possible of course).

- [x] 1 webapp
- [x] 2 responsive ui/webworker
- [x] 3 react/web forms
- [x] 4 plotting/vega
- [x] 5 integration?

**Comment by sverhoeven** [comment]
Requirements for equation:
* integers in equation
* axis should be square same tick interval
* ok to have nan for root

**Comment by sverhoeven** [comment]
Use vega spec to render plot of web assembly blog.

**Comment by sverhoeven** [comment]
To create a new figure goto https://vega.github.io/editor and paste in content of https://github.com/NLESC-JCER/run-cpp-on-web/raw/master/js-plot/vega-spec.json, and remove the iteration layer then put in the new equation ranges and root. The resulting json file should be saved in repo together with svg export.

**Comment by sverhoeven** [comment]
New equation plotted with as vega plot https://vega.github.io/editor/#/gist/25d0df5238e989215d3ac1be453a3d61/spec.json

![visualization](https://user-images.githubusercontent.com/1713488/92907437-9e98c200-f425-11ea-8569-a420c6bbb67a.png)

Tried to get tick interval same pixel size, but failed.

**Comment by jspaaks** [comment]
is the size or aspect ratio of the generated plot predefined? If so, we can calculated the axes limits that will yield a 1:1 ratio that is at 45 degrees.

**Comment by jspaaks** [comment]
Done for first blog. Does that mean we can close this issue? I unassigned myself and removed this issue from the milestone.

**Comment by sverhoeven** [comment]
Will be completed in #68
