### ISSUE TITLE
Create draft blog on medium

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#34]
Start with web assembly blog

**Comment by sverhoeven** [comment]
Try out https://markdowntomedium.com/

**Comment by fdiblen** [comment]
https://markdowntomedium.com/ requires rw permissions to GitHub account so we are not going to use it. 
Some changes are needed for the Medium post:
1. We need to add links to the captions
1. Mention only C++ not C/C++
1. Change some variable types to float
1. We **may** want to have newtonraphson.hpp and remove cpp file to have the class definition in a single file
1. We need to create gits got each code block
1. In the footer:
      - we need to add links to the next blog posts
      - we need to mention GT (and contact details?)

**Comment by jspaaks** [comment]
@fdiblen when making these lists, please use numbered lists, so we can more easily say "I agree with 1 and 3 but not 7" or something.

**Comment by sverhoeven** [comment]
1 - 3 All agree, make it so
4. all disagree, keep as is
5.  will do see #24 
6.1 Of course. Use hash in nlesc medium account to get links
6.2 `Blog was written by generalization team at NLeSC consisting of Stefan, Faruk, Jurriaan, Adam and Christiaan. I want to say thanks to Lourens Veen and Patrick Bos. Their useful comments definitely improved the clarity of the final text.`

**Comment by fdiblen** [comment]
Progress:
- [x] We need to add links to the captions
- [x] Mention only C++ not C/C++
- [x] Change some variable types to float
- [x] We need to create gits got each code block
- [x] In the footer:
  - [x] we need to add links to the next blog posts
  - [x] we need to mention GT (and contact details?)

**Comment by fdiblen** [comment]
Modifications mentioned in the comment above was made. The draft of the post was created. I will send the link by email.
