### ISSUE TITLE
Blog titles

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#42]
The blog should have titles:
1. web assembly, small static web page without user interaction
2. unblock ui with web worker, how to deal with tasks that take longer to complete
3. interactive form with React, gathering user inputs through a form in a simple react app
4. plot with Vega, displaying results from the algorithm in a more complex web app
5. blog which combines web-worker, form with React and plot with vega into single example

Add your title suggestions below, refer to blog number. Use single comment for each commiter

**Comment by sverhoeven** [comment]
1. Run C++ in a web browser: Look mom, no server
2. Run C++ in a web browser: Help my computation is freezing my browser
3. Run C++ in a web browser: Give me something to change & click
4. Run C++ in a web browser: A plot is worth a thousands words
5. Run C++ in a web browser: Kitchen sink edition

**Comment by fdiblen** [comment]
1. Run your C++ code in a web-browser: Converting your code to a web application
1. Run your C++ code in a web-browser: Forcing your web application to listen its master (you)
1. Run your C++ code in a web-browser: A more playful web application using web form
1. Run your C++ code in a we-browser: See the invisible, plot the data
1. Run your C++ code in a web-browser: The big picture, complete application

**Comment by jspaaks** [comment]
All of these titles are pretty long though, and will make it difficult for a reader to distinguish one from the other. On the app they will basically show up as 

1. Run your C++ code in a web-browser...
1. Run your C++ code in a web-browser...
1. Run your C++ code in a web-browser...
1. Run your C++ code in a web-browser...
1. Run your C++ code in a web-browser...

**Comment by jspaaks** [comment]
1.
   - Look mom, no server: C++ in the browser
   - Look mom, no server: run your C++ in the browser
   - Using C++ from a web application
   - Using C++ from a web application with WebAssembly
1. Responsive C++ in the browser using web workers
1. Interactive C++ in the browser
1. Spice up your C++ with web visualization
1. C++ in the browser: a complete application

**Comment by sverhoeven** [comment]
Shorter prefixes:
* C++ in browser
* C++ on the web
* C++ web app

**Comment by sverhoeven** [comment]
In medium you can have a subtitle, https://help.medium.com/hc/en-us/articles/214895188-Custom-titles-subtitles

**Comment by sverhoeven** [comment]
Chose titles are:

1. Using C++ in a web app with WebAssembly
2. Help! My C++ web app is not responding
3. Interact with your C++ web app using React forms
4. Spice up your C++ web app with visualizations
5. C++ web app with WebAssembly, Vega, Web Worker and React

**Comment by sverhoeven** [comment]
Renamed directories to:
1. webassembly 
2. web-worker
3. react
4. vega
5. kitchen-sink

**Comment by sverhoeven** [comment]
Please claim blog to change title of

* webassembly @jspaaks 
* web-worker @jspaaks 
* react @jspaaks 
* vega @sverhoeven 
* kitchen-sink @fdiblen

**Comment by sverhoeven** [comment]
All titles have set
