### ISSUE TITLE
Add schematic for blog 2

### ISSUE THREAD

**Issue by cwmeijer** [NLESC-JCER/run-cpp-on-web#54]
Something like
![image](https://user-images.githubusercontent.com/6087314/93313526-ded2b880-f808-11ea-9dbc-f44c4d503279.png)
More emphasis on UI though.

**Comment by sverhoeven** [comment]
To be more chronologically correct for the blog post, switch the postmessages around, so main thread does a postmessage first to trigger work and later worker thread sends message back. (Comment lifted from #40)

**Comment by sverhoeven** [comment]
Schema is part of master branch now
