### ISSUE TITLE
Use link instead of long code blocks

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#60]
Some code blocks are quite long. Some reviewers commented that

* they are intimitidated by long code block which are not in their preferred language
* medium blogs have reading minutes attached to them, which might make blog post a longer read then expected

Certain long code blocks of should be replaced with links.

**Comment by sverhoeven** [comment]
1. [x] web assembly
1. [x] web worker
1. [x] react
1. [x] vega
1. [x] all of it

**Comment by fdiblen** [comment]
done for react post in 85f3a57040b7c1404f71043f3f7105af789c7c4f
