### ISSUE TITLE
Plot looks too minimal

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#61]
To attract users to vega we should make the plot look like the readers expect. Include title, units etc.

**Comment by sverhoeven** [comment]
Lets add for each vega plot

1. [ ] title
1. [ ] add `f(x)` to y-axis
1. [ ] description

**Comment by jspaaks** [comment]
FWIW There is a top level ``config`` property, that can be used to unclutter some of the code. I havent figured out how to apply this to axis labels or the ``root_rule``.

```
"config": {
  "axis": {"labelFontSize": 20, "labelFontWeight": "lighter"},
  "title": {"fontSize": 20}
}, 
```

**Comment by jspaaks** [comment]
BTW what do you mean with "description"?

**Comment by sverhoeven** [comment]
Description is a field on document level see https://vega.github.io/vega-lite/docs/spec.html#common

**Comment by sverhoeven** [comment]
Done with #78
