### ISSUE TITLE
Tease final web application in intro of first blog

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#62]
I would be nice to tease reader what the final web application will look like in the first blog post

**Comment by jspaaks** [comment]
My suggestion would be to include a link to the full working example at the bottom, where we give the reader options, i.e. after _We'll wrap up the series in a final blog that combines the topics of the whole series in a full-featured web application._

**Comment by jspaaks** [comment]
Done
