### ISSUE TITLE
Determine tags for each blog

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/run-cpp-on-web#83]
Medium stories can have tags. We should use them for our benefit.

**Comment by fdiblen** [comment]
Blog 1: C++, JavaScript, WebAssembly, algorithms, web development
Blog 2: C++, JavaScript, Web workers, algorithms, web development
Blog 3: C++, JavaScript, React, web development
Blog 4: C++, JavaScript, React, visualization, interactive app, web development
Blog 5: C++, JavaScript, algorithms, React, visualization, interactive app, web development

**Comment by sverhoeven** [comment]
To add to @fdiblen list:
* Blog 1: Emscripten
* Blog 4: Vega Lite

There is a max of 5 tags per story. So we will need to drop `web development` from those.
